In [1]:
import numpy as np

In [2]:
one_dim = np.array([1,2,3,4])
one_dim

array([1, 2, 3, 4])

In [3]:
one_dim.ndim

1

In [4]:
two_dim = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
two_dim

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
two_dim.ndim

2

In [6]:
three_dim = np.array([[[1],[2],[3],[4]],[[1],[2],[3],[4]],[[1],[2],[3],[4]]])
three_dim

array([[[1],
        [2],
        [3],
        [4]],

       [[1],
        [2],
        [3],
        [4]],

       [[1],
        [2],
        [3],
        [4]]])

In [7]:
three_dim.ndim

3

# The confusion in the class

In [8]:
trial_1 = [1,2,3,4]
trial_2 = [5,6,7,8]

In [9]:
np_trial_1 = np.array(trial_1)
np_trial_2 = np.array(trial_2)

In [10]:
print(np_trial_1)
print(np_trial_1.ndim)

[1 2 3 4]
1


In [11]:
print(np_trial_2)
print(np_trial_2.ndim)

[5 6 7 8]
1


In [12]:
# correct
all_correct = np.array([np_trial_1,np_trial_2])
all_correct

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
all_correct.ndim

2

In [14]:
all_correct[1,0]

5

In [15]:
# wrong - ignoring that variables np_trial_1 & np_trial_2 have a square bracket with themselves
all_wrong = np.array([[np_trial_1],[np_trial_2]])
all_wrong

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [16]:
all_wrong.ndim

3

In [17]:
all_wrong[1] # notice the extra square bracket here

array([[5, 6, 7, 8]])

In [18]:
all_wrong[1,0]

array([5, 6, 7, 8])

In [19]:
all_wrong[1,0,0]

5

# In the case of a list

In [20]:
x = [[[1,2,3],[4,5,6]]] # 3 dimensions
x[0]

[[1, 2, 3], [4, 5, 6]]

In [21]:
x[0][0]

[1, 2, 3]

In [22]:
x[0][0][0]

1